//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace likeothers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersResult
    {
        public int IdOption { get; set; }
        public int Amount { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
